version: '3.3'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    container_name: bike-rent-db
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - bike-rent-db:/var/lib/mysql

  app:
    depends_on:
      - db
    build: ../
    container_name: bike-rent-api
    restart: unless-stopped
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    env_file: ./.env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: $MYSQLDB_LOCAL_PORT
      DB_NAME: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      SERVER_PORT: $SPRING_LOCAL_PORT
    volumes:
      - .m2:/root/.m2


volumes:
  bike-rent-db: